<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>my promise</h1>
    <script>
        const PENDING = 'pending';
        const RESOLVED = 'resolved';
        const REJECTED = 'rejected';
        function MyPromise(fn){
            this.status = PENDING;
            this.value = null;
            this.error = null;

            this.resolvedCallbacks = [];
            this.rejectCallbacks = [];

            this.resolve = res =>{
                console.log("异步方法，执行完成，触发resolve")
                if(this.status === PENDING){
                    this.status = RESOLVED;
                    this.value = res;
                    this.resolvedCallbacks.map( cb => cb(res));
                }
            }
            this.reject = err =>{
                console.log("异步方法，执行出错，触发reject")
                if(this.status === PENDING){
                    this.status = REJECTED;
                    this.error = err;
                    this.rejectCallbacks.map( cb => cb(err));
                }
            }

            try{
                console.log("promise同步执行");
                fn(this.resolve, this.reject);
            } catch(e){
                this.reject(e);
            }
        }
        MyPromise.prototype.then = function(resolveCb, rejectCb){
            console.log("注册回调方法开始");
            if(this.status === PENDING){
                console.log("将回调方法加入到对应的callback数组中")
                this.resolvedCallbacks.push(resolveCb);
                this.rejectCallbacks.push(rejectCb);
            }

            if(this.status === RESOLVED){
                console.log("同步方法，执行resolve回调方法")
                resolveCb(this.value);
            }

            if(this.status === REJECTED){
                console.log("同步方法，执行reject回调方法")
                rejectCb(this.error);
            }
            return this;
        }

        const promiseTest = new MyPromise((resolve,reject)=>{
            setTimeout(()=>{
                resolve("执行成功1000");
            }, 1000);
        });
        promiseTest.then((res) => {
            console.log("结果：", res);
            return "第一个then的结果：" + res;
        },(error)=>{
            console.log("错误提示:", error);
        }).then((res)=>{
            console.log("怎么还有啊:", res);
        })

        function promisify(fn){
            return function(...args){
                return new promise(function(resolve, reject){
                    var res = fn.apply(this, args);
                    resolve(res);
                })
            }
        }

        //https://mp.weixin.qq.com/s/qdJ0Xd8zTgtetFdlJL3P1g
        function Promise(func){
            this.state = PENDING;       // Promise的状态
            this.result = null;         // 成功的 和 错误的结果
            this.callbacks = [];

            let onFulfilled = value => transition(this, FULFILLED, value);
            let onRejected = value => transition(this, REJECTED, reason);

            let ignore = false;
            let resolve = value => {
                if (ignore) return;
                ignore = true;
                resolvePromise(this, value, onFulfilled, onRejected);
            }
            let reject = reason => {
                if (ignore) return;
                ignore = true;
                onRejected(reason);
            }

            try {
                func(resolve, reject);
            } catch (error) {
                reject(error);
            }
        }

        //对promise进行状态转移
        const transition = (promise, state, result) => {
            if(promise.state !== PENDING) return;
            promise.state = state;
            promise.result = result;
        }

        Promise.prototype.then = function(onFulfilled, onRejected){
            return new Promise((resolve, reject) => {
                let callback = { onFulfilled, onRejected, resolve, reject };
                if(this.state === PENDING){
                    this.callbacks.push(callback);
                }else{
                    setTimeout(()=> handleCallback(callback, this.state, this.result), 0);
                }
            })
        }
        //在当前promise和下一个promise之间进行状态传递
        const handleCallback = (callback, state, result) => {
            let { onFulfilled, onRejected, resolve, reject } = callback;
            try {
                if(state === RESOLVED){
                    isFunction(onFulfilled)? resolve(onFulfilled(result)) : resolve(result);
                }else if(state === REJECTED){
                    isFunction(onRejected)? resolve(onRejected(result)) : reject(result);
                }
            } catch (error) {
                reject(error);
            }
        }
        //对特殊状态的result进行处理
        const resolvePromise = (promise, result, resolve, reject) => {
            if(result === promise){
                let reason = new TypeError('Can not fufill promise with itself');
                return reject(reason);
            }

            if(isPromise(result)){
                return result.then(resolve, reject);
            }

            if(isThenable(result)){
                try {
                    let then = result.then;
                    if(isFunction(then)){
                        return new Promise(then.bind(result)).then(resolve, reject);
                    }
                } catch (error) {
                    return reject(error);
                }
            }
            //
            resolve(result);
        }
    </script>
</body>
</html>